### ISSUE TITLE
No control over keyboard

### ISSUE THREAD

**Issue by aculnaig** [SimonLarsen/mrrescue#10]
<b>Manjaro Linux 3.18.20-1</b>
<b>Microsoft Wireless Desktop 800</b>
<b>mrrescue source code cloned with git </b>

When I start up the game, just after the main menu comes up, the keyboard seems to be possessed and the left arrow keep rolling up non-stop forever.

This is the situation ( i made a GIF )

http://fat.gfycat.com/LivelyCostlyDoe.gif

When I unplug the keyboard It stops rolling but I tried different USB ports, with no luck, same result, keep rolling.

EDIT: As a bug test comparison, I also tried to run Sienna and worked perfectly, no problem at all. So, maybe the problem is up to Mr. Rescue.

**Comment by SimonLarsen** [comment]
Hi aculnaig. I apologize for the very late reply.

My best guess is that it might be receiving garbage data from one of the joysticks.
To check whether this is the case you can add a "return" statement after 147 in main.lua so it ends up like this

```lua
function updateKeys()
	-- Check keyboard keys
	for action, key in pairs(config.keys) do
		if love.keyboard.isDown(key) then
			keystate[action] = true
		else
			keystate[action] = false
		end
	end

	return -- RETURN BEFORE READING JOYSTICK

	-- Check joystick axes
	local joystick = love.joystick.getJoysticks()[1]
```
