### ISSUE TITLE
Upgrade 0.10

### ISSUE THREAD

**Issue by mongrol** [SimonLarsen/mrrescue#12]
Please upgrade Mr Rescue to Love 0.10 so I can upgrade the Debian package. It appears you have a pull request with some patches for this. I assume they'll need proper testing to ensure those minor changes are all that's needed.

**Comment by SimonLarsen** [comment]
Should be good to go now. ^_^

**Comment by mongrol** [comment]
Ta Simon.

Simon Larsen writes:

> Should be good to go now. ^_^
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/SimonLarsen/mrrescue/issues/12#issuecomment-170381822

-- 
Steven Hamilton
I don't look like two zombies
